unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Posição da barra
set -g status-position bottom

# Frequência de atualização (em segundos)
set -g status-interval 5

# Cores base (Estilo Minimalista/Synthwave)
set -g status-style 'bg=#1e1e2e fg=#cdd6f4' # Fundo escuro, texto claro

# Exibe o nome da sessão em destaque
set -g status-left-length 30
set -g status-left "#[bg=#89b4fa,fg=#1e1e2e,bold] 󰒋 #S #[bg=default,fg=#89b4fa]"

# Exibe o nome da sessão em destaque
set -g status-left-length 30
set -g status-left "#[bg=#89b4fa,fg=#1e1e2e,bold] 󰒋 #S #[bg=default,fg=#89b4fa]"
